Shmuel mafia router
amichai-bd/fpga_mafia pull request #254
Opened 2023-05-02 19:51 UTC by ShmuelSfez

fixed important bugs, need to insert to main.
plus added support for in_ready_arb signals.

2023-05-02 20:32 UTC, amichai-bd requested changes
Please review comments. Fix the macro so the cache level0 will pass

2023-05-02 20:32 UTC, amichai-bd commented on source/common/macros.sv
> +`define  ENCODER(encoded , decoded )             \
By changing a common macro, the cache ip has failed.
If you felt like you don't need the valid bit output as part of your use case, you may keep it unused .
The valid is actually useful for the cases where the encoder needs to make sure the data is actually correct. Otherwise what is the encoded version of 4'b0000 ve 4'b0001 - both will be 2'b00. But one will result with valid and the other without.

2023-05-02 20:32 UTC, amichai-bd commented on source/router/arbiter.sv
Let's review these changes together.. we can fix this up a little.

I also think we should separate the "mux" data path from the selector which is the round Robin algorithm + taking the ready into consideration

2023-05-02 20:32 UTC, amichai-bd commented on source/router/fifo.sv
> -assign full  = (wr_ptr == (rd_ptr-1'b1));
What was wrong with the -1?

2023-05-03 19:37 UTC, ShmuelSfez commented on source/router/fifo.sv
> -assign full  = (wr_ptr == (rd_ptr-1'b1));
it did not take into consideration the hysteresis, some tests were failing when the wr_ptr was in 2 (for FIFO_DEPTH = 3) and rd_ptr was in 0 so the full didnt go up. (actually the empty signal got up in the next push_data because of that.)

2023-05-03 19:49 UTC, amichai-bd commented on source/router/fifo.sv
> -assign full  = (wr_ptr == (rd_ptr-1'b1));
That is an issue when the fifo is not a multiple of 2 -> this is why I changed the default value to 4 instead of 3. (you changed it back to 3 - probably accidentally)

I think we might want to move back to a counter implementation of FIFO instead of a FIFO rd<->wr ptr compare.
Lets talk about it next week

2023-05-03 19:49 UTC, merged